apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service3
  name: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - image: aaboungab/s3:k8
        name: s3
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP


