apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service4
  name: service4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - image: aaboungab/s4:k8
        name: s4
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports: 
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP


