apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - image: aaboungab/s1:k8
        name: s1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer


