apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service2
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - image: aaboungab/s2:k8
        name: s2
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
