apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-07T17:44:39Z"
  labels:
    app: mysql
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3306,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-01-07T17:44:39Z"
  name: mysql
  namespace: default
  resourceVersion: "42506"
  selfLink: /api/v1/namespaces/default/services/mysql
  uid: 5abb3e4f-7ef0-4ad1-bdf6-37ad4b8bdf09
spec:
  clusterIP: 10.0.252.126
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
